# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'basic_sweep.ui'
#
# Created: Tue Aug 26 09:52:46 2014
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_SweepDialog(object):
    def setupUi(self, SweepDialog):
        SweepDialog.setObjectName(_fromUtf8("SweepDialog"))
        SweepDialog.resize(1020, 830)
        self.horizontalLayout_17 = QtGui.QHBoxLayout(SweepDialog)
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.plot_group_box = QtGui.QGroupBox(SweepDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.plot_group_box.sizePolicy().hasHeightForWidth())
        self.plot_group_box.setSizePolicy(sizePolicy)
        self.plot_group_box.setAutoFillBackground(False)
        self.plot_group_box.setFlat(False)
        self.plot_group_box.setObjectName(_fromUtf8("plot_group_box"))
        self.horizontalLayout_17.addWidget(self.plot_group_box)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.groupBox = QtGui.QGroupBox(SweepDialog)
        self.groupBox.setFlat(True)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.spin_start_freq = QtGui.QDoubleSpinBox(self.groupBox)
        self.spin_start_freq.setDecimals(3)
        self.spin_start_freq.setMaximum(240.0)
        self.spin_start_freq.setProperty("value", 140.0)
        self.spin_start_freq.setObjectName(_fromUtf8("spin_start_freq"))
        self.horizontalLayout.addWidget(self.spin_start_freq)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        self.spin_stop_freq = QtGui.QDoubleSpinBox(self.groupBox)
        self.spin_stop_freq.setFrame(True)
        self.spin_stop_freq.setDecimals(3)
        self.spin_stop_freq.setMaximum(240.0)
        self.spin_stop_freq.setProperty("value", 161.0)
        self.spin_stop_freq.setObjectName(_fromUtf8("spin_stop_freq"))
        self.horizontalLayout_2.addWidget(self.spin_stop_freq)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_3.addWidget(self.label_3)
        self.combo_step_size = QtGui.QComboBox(self.groupBox)
        self.combo_step_size.setEditable(True)
        self.combo_step_size.setObjectName(_fromUtf8("combo_step_size"))
        self.combo_step_size.addItem(_fromUtf8(""))
        self.combo_step_size.addItem(_fromUtf8(""))
        self.combo_step_size.addItem(_fromUtf8(""))
        self.combo_step_size.addItem(_fromUtf8(""))
        self.combo_step_size.addItem(_fromUtf8(""))
        self.combo_step_size.addItem(_fromUtf8(""))
        self.combo_step_size.addItem(_fromUtf8(""))
        self.horizontalLayout_3.addWidget(self.combo_step_size)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_11.addWidget(self.label_5)
        self.spin_subsweeps = QtGui.QSpinBox(self.groupBox)
        self.spin_subsweeps.setMinimum(1)
        self.spin_subsweeps.setMaximum(200)
        self.spin_subsweeps.setObjectName(_fromUtf8("spin_subsweeps"))
        self.horizontalLayout_11.addWidget(self.spin_subsweeps)
        self.verticalLayout_2.addLayout(self.horizontalLayout_11)
        self.push_start_sweep = QtGui.QPushButton(self.groupBox)
        self.push_start_sweep.setAutoDefault(False)
        self.push_start_sweep.setObjectName(_fromUtf8("push_start_sweep"))
        self.verticalLayout_2.addWidget(self.push_start_sweep)
        self.push_abort = QtGui.QPushButton(self.groupBox)
        self.push_abort.setAutoDefault(False)
        self.push_abort.setObjectName(_fromUtf8("push_abort"))
        self.verticalLayout_2.addWidget(self.push_abort)
        self.label_coarse_info = QtGui.QLabel(self.groupBox)
        self.label_coarse_info.setObjectName(_fromUtf8("label_coarse_info"))
        self.verticalLayout_2.addWidget(self.label_coarse_info)
        self.horizontalLayout_5.addLayout(self.verticalLayout_2)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_5)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(SweepDialog)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_7.addWidget(self.label_4)
        self.line_span_hz = QtGui.QLineEdit(self.groupBox_2)
        self.line_span_hz.setObjectName(_fromUtf8("line_span_hz"))
        self.horizontalLayout_7.addWidget(self.line_span_hz)
        self.verticalLayout_7.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_6 = QtGui.QLabel(self.groupBox_2)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_8.addWidget(self.label_6)
        self.line_npoints = QtGui.QLineEdit(self.groupBox_2)
        self.line_npoints.setObjectName(_fromUtf8("line_npoints"))
        self.horizontalLayout_8.addWidget(self.line_npoints)
        self.verticalLayout_7.addLayout(self.horizontalLayout_8)
        self.label_spacing = QtGui.QLabel(self.groupBox_2)
        self.label_spacing.setObjectName(_fromUtf8("label_spacing"))
        self.verticalLayout_7.addWidget(self.label_spacing)
        self.push_start_fine_sweep = QtGui.QPushButton(self.groupBox_2)
        self.push_start_fine_sweep.setAutoDefault(False)
        self.push_start_fine_sweep.setObjectName(_fromUtf8("push_start_fine_sweep"))
        self.verticalLayout_7.addWidget(self.push_start_fine_sweep)
        self.horizontalLayout_10.addLayout(self.verticalLayout_7)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.check_use_cal = QtGui.QCheckBox(SweepDialog)
        self.check_use_cal.setChecked(True)
        self.check_use_cal.setObjectName(_fromUtf8("check_use_cal"))
        self.verticalLayout_3.addWidget(self.check_use_cal)
        self.progress_sweep = QtGui.QProgressBar(SweepDialog)
        self.progress_sweep.setProperty("value", 24)
        self.progress_sweep.setObjectName(_fromUtf8("progress_sweep"))
        self.verticalLayout_3.addWidget(self.progress_sweep)
        self.plainTextEdit = QtGui.QPlainTextEdit(SweepDialog)
        self.plainTextEdit.setObjectName(_fromUtf8("plainTextEdit"))
        self.verticalLayout_3.addWidget(self.plainTextEdit)
        spacerItem = QtGui.QSpacerItem(20, 13, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.label_7 = QtGui.QLabel(SweepDialog)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_13.addWidget(self.label_7)
        self.spin_dbm_per_tone = QtGui.QDoubleSpinBox(SweepDialog)
        self.spin_dbm_per_tone.setDecimals(1)
        self.spin_dbm_per_tone.setMinimum(-140.0)
        self.spin_dbm_per_tone.setMaximum(0.0)
        self.spin_dbm_per_tone.setSingleStep(0.5)
        self.spin_dbm_per_tone.setProperty("value", -50.0)
        self.spin_dbm_per_tone.setObjectName(_fromUtf8("spin_dbm_per_tone"))
        self.horizontalLayout_13.addWidget(self.spin_dbm_per_tone)
        self.verticalLayout_3.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.label_8 = QtGui.QLabel(SweepDialog)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_14.addWidget(self.label_8)
        self.line_dac_gain = QtGui.QLineEdit(SweepDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_dac_gain.sizePolicy().hasHeightForWidth())
        self.line_dac_gain.setSizePolicy(sizePolicy)
        self.line_dac_gain.setMinimumSize(QtCore.QSize(50, 0))
        self.line_dac_gain.setMaximumSize(QtCore.QSize(50, 16777215))
        self.line_dac_gain.setBaseSize(QtCore.QSize(0, 0))
        self.line_dac_gain.setObjectName(_fromUtf8("line_dac_gain"))
        self.horizontalLayout_14.addWidget(self.line_dac_gain)
        self.verticalLayout_3.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.label_10 = QtGui.QLabel(SweepDialog)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_18.addWidget(self.label_10)
        self.line_dac_atten = QtGui.QLineEdit(SweepDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_dac_atten.sizePolicy().hasHeightForWidth())
        self.line_dac_atten.setSizePolicy(sizePolicy)
        self.line_dac_atten.setMinimumSize(QtCore.QSize(50, 0))
        self.line_dac_atten.setMaximumSize(QtCore.QSize(50, 16777215))
        self.line_dac_atten.setBaseSize(QtCore.QSize(0, 0))
        self.line_dac_atten.setReadOnly(True)
        self.line_dac_atten.setObjectName(_fromUtf8("line_dac_atten"))
        self.horizontalLayout_18.addWidget(self.line_dac_atten)
        self.verticalLayout_3.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.label_9 = QtGui.QLabel(SweepDialog)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_15.addWidget(self.label_9)
        self.line_adc_gain = QtGui.QLineEdit(SweepDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_adc_gain.sizePolicy().hasHeightForWidth())
        self.line_adc_gain.setSizePolicy(sizePolicy)
        self.line_adc_gain.setMaximumSize(QtCore.QSize(50, 16777215))
        self.line_adc_gain.setObjectName(_fromUtf8("line_adc_gain"))
        self.horizontalLayout_15.addWidget(self.line_adc_gain)
        self.verticalLayout_3.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16.addLayout(self.verticalLayout_3)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_status = QtGui.QLabel(SweepDialog)
        self.label_status.setObjectName(_fromUtf8("label_status"))
        self.verticalLayout.addWidget(self.label_status)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.push_add_resonator = QtGui.QPushButton(SweepDialog)
        self.push_add_resonator.setObjectName(_fromUtf8("push_add_resonator"))
        self.horizontalLayout_9.addWidget(self.push_add_resonator)
        self.push_clear_all = QtGui.QPushButton(SweepDialog)
        self.push_clear_all.setAutoDefault(False)
        self.push_clear_all.setObjectName(_fromUtf8("push_clear_all"))
        self.horizontalLayout_9.addWidget(self.push_clear_all)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.push_save_res = QtGui.QPushButton(SweepDialog)
        self.push_save_res.setObjectName(_fromUtf8("push_save_res"))
        self.horizontalLayout_12.addWidget(self.push_save_res)
        self.push_load_res = QtGui.QPushButton(SweepDialog)
        self.push_load_res.setObjectName(_fromUtf8("push_load_res"))
        self.horizontalLayout_12.addWidget(self.push_load_res)
        self.verticalLayout.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_16.addLayout(self.verticalLayout)
        self.verticalLayout_4.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.push_save = QtGui.QPushButton(SweepDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.push_save.sizePolicy().hasHeightForWidth())
        self.push_save.setSizePolicy(sizePolicy)
        self.push_save.setAutoDefault(False)
        self.push_save.setObjectName(_fromUtf8("push_save"))
        self.horizontalLayout_4.addWidget(self.push_save)
        self.line_filename = QtGui.QLineEdit(SweepDialog)
        self.line_filename.setReadOnly(True)
        self.line_filename.setObjectName(_fromUtf8("line_filename"))
        self.horizontalLayout_4.addWidget(self.line_filename)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_17.addLayout(self.verticalLayout_4)

        self.retranslateUi(SweepDialog)
        self.combo_step_size.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(SweepDialog)

    def retranslateUi(self, SweepDialog):
        SweepDialog.setWindowTitle(_translate("SweepDialog", "mm-wave source sweeper", None))
        self.groupBox.setTitle(_translate("SweepDialog", "Coarse Sweep", None))
        self.label.setText(_translate("SweepDialog", "Start:", None))
        self.spin_start_freq.setSuffix(_translate("SweepDialog", " GHz", None))
        self.label_2.setText(_translate("SweepDialog", "Stop:", None))
        self.spin_stop_freq.setSuffix(_translate("SweepDialog", " GHz", None))
        self.label_3.setText(_translate("SweepDialog", "Step:", None))
        self.combo_step_size.setItemText(0, _translate("SweepDialog", "10 MHz", None))
        self.combo_step_size.setItemText(1, _translate("SweepDialog", "25 MHz", None))
        self.combo_step_size.setItemText(2, _translate("SweepDialog", "50 MHz", None))
        self.combo_step_size.setItemText(3, _translate("SweepDialog", "100 MHz", None))
        self.combo_step_size.setItemText(4, _translate("SweepDialog", "250 MHz", None))
        self.combo_step_size.setItemText(5, _translate("SweepDialog", "500 MHz", None))
        self.combo_step_size.setItemText(6, _translate("SweepDialog", "1.00 GHz", None))
        self.label_5.setText(_translate("SweepDialog", "Repeat sweep # times:", None))
        self.push_start_sweep.setText(_translate("SweepDialog", "Start Sweep", None))
        self.push_abort.setText(_translate("SweepDialog", "Abort Sweep", None))
        self.label_coarse_info.setText(_translate("SweepDialog", "Spacing:", None))
        self.groupBox_2.setTitle(_translate("SweepDialog", "Fine Sweep", None))
        self.label_4.setText(_translate("SweepDialog", "Span (Hz):", None))
        self.line_span_hz.setText(_translate("SweepDialog", "20000", None))
        self.label_6.setText(_translate("SweepDialog", "Points:", None))
        self.line_npoints.setText(_translate("SweepDialog", "20", None))
        self.label_spacing.setText(_translate("SweepDialog", "Spacing:", None))
        self.push_start_fine_sweep.setText(_translate("SweepDialog", "Start Fine Sweep", None))
        self.check_use_cal.setText(_translate("SweepDialog", "Use Calibration", None))
        self.progress_sweep.setFormat(_translate("SweepDialog", "Sweep Progress: %p%", None))
        self.label_7.setText(_translate("SweepDialog", "Power level:", None))
        self.spin_dbm_per_tone.setSuffix(_translate("SweepDialog", " dBm/tone", None))
        self.label_8.setText(_translate("SweepDialog", "DAC Gain (dB):", None))
        self.label_10.setText(_translate("SweepDialog", "DAC Atten (dB):", None))
        self.label_9.setText(_translate("SweepDialog", "ADC Gain (dB):", None))
        self.label_status.setText(_translate("SweepDialog", "status", None))
        self.push_add_resonator.setText(_translate("SweepDialog", "Add Selected", None))
        self.push_clear_all.setText(_translate("SweepDialog", "Clear All", None))
        self.push_save_res.setText(_translate("SweepDialog", "Save...", None))
        self.push_load_res.setText(_translate("SweepDialog", "Load...", None))
        self.push_save.setText(_translate("SweepDialog", "Start Logging", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    SweepDialog = QtGui.QDialog()
    ui = Ui_SweepDialog()
    ui.setupUi(SweepDialog)
    SweepDialog.show()
    sys.exit(app.exec_())

